// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from full

package com.clemble.social.provider.data.callback.delivery;

public enum DeliveryChannel {
    HTTP(0);

    public final int number;

    private DeliveryChannel(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static DeliveryChannel valueOf(int number) {
        switch (number) {
        case 0:
            return HTTP;
        default:
            return null;
        }
    }
}
