DROP TABLE IF EXISTS `PROFILE_TO_SOCIAL_PROFILES`;

CREATE TABLE `PROFILE_TO_SOCIAL_PROFILES` (
  `PROFILE_ID` varchar(50),
  `PRIMARY_CONNECTION` varchar(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `PROFILES`;

CREATE TABLE `PROFILES` (
  `PROFILE_ID` varchar(50),
  PRIMARY KEY (`PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `SOCIAL_PERSON_CONNECTIONS`;

CREATE TABLE `SOCIAL_PERSON_CONNECTIONS` (
  `PRIMARY_CONNECTION` varchar(100),
  `CONNECTION` varchar(100),
  PRIMARY KEY (`PRIMARY_CONNECTION`,`CONNECTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `SOCIAL_PERSON_PROFILES`;

CREATE TABLE `SOCIAL_PERSON_PROFILES` (
  `PRIMARY_CONNECTION` varchar(100),
  `FIRST_NAME` varchar(256),
  `LAST_NAME` varchar(256),
  `PROFILE_URL` varchar(256),
  `PROFILE_IMAGE` varchar(256),
  `BIRTH_DAY` int(11),
  `BIRTH_MONTH` int(11),
  `BIRTH_YEAR` int(11),
  `GENDER` varchar(1),
  PRIMARY KEY (`PRIMARY_CONNECTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `USER_TO_CONNECTIONS`;

CREATE TABLE `USER_TO_CONNECTIONS` (
  `USER_ID` varchar(50),
  `PROFILE_ID` varchar(50),
  PRIMARY KEY (`USER_ID`,`PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `USER_ID` varchar(50),
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;