DROP TABLE IF EXISTS `UTILS_NAME_VOCABULARY`;

CREATE TABLE `UTILS_NAME_VOCABULARY` (
  `WORD` varchar(255),
  `TRANSLATION` varchar(255),
  `PROVIDER` varchar(50),
  PRIMARY KEY (`WORD`,`PROVIDER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `UTILS_SOUND_MATCHES`;

CREATE TABLE `UTILS_SOUND_MATCHES` (
  `WORD` varchar(255),
  `PRESENTATION` varchar(255),
  `ALGORITHM` varchar(50),
  PRIMARY KEY (`WORD`,`ALGORITHM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `UTILS_SYNONYMS`;

CREATE TABLE `UTILS_SYNONYMS` (
  `WORD` varchar(255),
  `SEQUENCE` varchar(255),
  PRIMARY KEY (`WORD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;